# Generated by Django 3.1.2 on 2021-02-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actor", "0001_initial"),
        ("core", "0001_initial"),
        ("genre", "0002_auto_20210117_1530"),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tvfy_code", models.CharField(max_length=14)),
                ("name", models.CharField(max_length=255)),
                ("creator", models.CharField(blank=True, max_length=128, null=True)),
                ("run_time", models.IntegerField(blank=True, null=True)),
                ("storyline", models.TextField()),
                ("release_date", models.DateField()),
                ("is_active", models.BooleanField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("tv_network", models.CharField(blank=True, max_length=255, null=True)),
                ("wins", models.IntegerField(blank=True, default=0, null=True)),
                ("nominations", models.IntegerField(blank=True, default=0, null=True)),
                ("season_count", models.IntegerField(blank=True, null=True)),
                ("imdb_rate", models.FloatField(blank=True, null=True)),
                ("imdb_vote_count", models.IntegerField(blank=True, null=True)),
                (
                    "imdb_popularity",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("tv_com_rate", models.FloatField(blank=True, null=True)),
                ("rt_tomatometer", models.IntegerField(blank=True, null=True)),
                ("rt_audience_rate", models.IntegerField(blank=True, null=True)),
                ("tvfy_rate", models.FloatField(blank=True, null=True)),
                ("tvfy_popularity", models.FloatField(blank=True, null=True)),
                ("imdb_url", models.URLField(blank=True, null=True)),
                ("tv_network_url", models.URLField(blank=True, null=True)),
                ("rotten_tomatoes_url", models.URLField(blank=True, null=True)),
                ("country", models.ManyToManyField(to="core.Country")),
                ("genres", models.ManyToManyField(to="genre.Genre")),
                ("language", models.ManyToManyField(to="core.Language")),
            ],
        ),
        migrations.CreateModel(
            name="SeriesCast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_name", models.CharField(default="John Doe", max_length=255)),
                ("episode_count", models.IntegerField(default=0)),
                ("start_acting", models.DateField(blank=True, null=True)),
                ("end_acting", models.DateField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="actor.actor"
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="series.series"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("imdb_url", models.URLField(blank=True, null=True)),
                ("imdb_season_average_rate", models.FloatField(blank=True, null=True)),
                ("tvfy_rate", models.FloatField(blank=True, null=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="series.series"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("storyline", models.TextField(blank=True, null=True)),
                ("release_date", models.DateField()),
                ("imdb_rate", models.FloatField(blank=True, null=True)),
                ("imdb_vote_count", models.IntegerField(default=0)),
                ("tvfy_rate", models.FloatField(blank=True, null=True)),
                ("tvfy_vote_count", models.FloatField(default=0)),
                ("episode", models.IntegerField(default=0)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="series.season"
                    ),
                ),
            ],
        ),
    ]
