# Generated by Django 3.1.2 on 2020-11-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb_rate', models.FloatField(blank=True, null=True)),
                ('rotten_tomatoes_rate', models.FloatField(blank=True, null=True)),
                ('subscription', models.CharField(blank=True, max_length=255, null=True)),
                ('run_time', models.IntegerField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('storyline', models.TextField()),
                ('release_data', models.DateField()),
                ('is_active', models.BooleanField()),
                ('artists', models.ManyToManyField(to='artist.Artist')),
                ('genres', models.ManyToManyField(to='genres.Genres')),
            ],
        ),
    ]
