# Generated by Django 3.1.2 on 2021-02-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("series", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="tvfy_code",
            field=models.CharField(db_index=True, max_length=14, unique=True),
        ),
    ]
