from setuptools import setup, find_packages

setup(
    name="TvFY",
    use_scm_version=True,
    setup_requires=["setuptools_scm", "setuptools"],
    url="https://github.com/cihankarluk/TvFY.git",
    description="TvFY is simply app for chill.",
    packages=find_packages(include=["tvfy*"]),
    author="Cihan Karluk",
    author_email="cihankarluk@gmail.com",
    install_requires=[
        "django",
        "djangorestframework",
        "django-filter",
        "django-environ",
        "python-dotenv==0.19.0",
        "psycopg2==2.9.3",
        "django-rest-framework==0.1.0",
        "requests==2.24.0",
        "beautifulsoup4==4.9.3",
        "backoff==2.0.1",
        "pre-commit==2.10.0",
        "model-bakery==1.3.2",
        "django-extensions==3.1.3",
        "aiohttp==3.7.4",
        "pytest-django",
        "drf-yasg",
        "django-click==2.3.0",
    ],
    python_requires=">=3.9.0",
    classifiers=[
        "Environment :: Web Environment",
        "Framework :: Django",
        "Operating System :: OS Independent",
        "Natural Language :: English",
        "Programming Language :: Python :: 3.9",
        "Topic :: Internet :: WWW/HTTP",
    ],
)
