# Generated by Django 3.1.2 on 2021-01-17 15:30
from django.db import migrations

from TvFY.core.helpers import read_file
from TvFY.genre.models import Genre


def create_genre_data(apps, schema_editor):
    json_file = read_file("fixtures/genres.json", is_json=True)
    for data in json_file:
        Genre.objects.create(**data["fields"])


class Migration(migrations.Migration):
    dependencies = [
        ("genre", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_genre_data)]
