# Generated by Django 3.1.2 on 2020-10-26 17:55

import TvFY.core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[TvFY.core.helpers.UnicodeUsernameValidator()]),
        ),
    ]
