version: "3.8"

services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tvfy
      POSTGRES_DB: tvfy
      POSTGRES_PASSWORD: tvfy

  migration:
    build: ..
    command: python manage.py migrate --noinput
    container_name: migrations
    depends_on:
      - postgres
    restart: on-failure

  api:
    build: ..
    image: tvfy
    command: python manage.py runserver 0.0.0.0:5000
    ports:
      - 5000:5000
    depends_on:
      - migration
    tty: true