# Generated by Django 4.0.4 on 2022-05-24 21:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, db_column='created_by', editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, db_column='updated_by', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('tvfy_code', models.CharField(db_index=True, max_length=11, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('imdb_url', models.URLField(unique=True)),
                ('born_date', models.DateTimeField(null=True)),
                ('died_date', models.DateTimeField(null=True)),
                ('perks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), null=True, size=None)),
                ('oscars', models.PositiveSmallIntegerField(null=True)),
                ('oscar_nominations', models.PositiveSmallIntegerField(null=True)),
                ('wins', models.PositiveSmallIntegerField(null=True)),
                ('nominations', models.PositiveSmallIntegerField(null=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('born_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_born_at', to='country.country')),
                ('died_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_died_at', to='country.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
