# Generated by Django 4.0.4 on 2022-06-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
        ('country', '0001_initial'),
        ('director', '0001_initial'),
        ('genre', '0001_initial'),
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, db_column='created_by', editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, db_column='updated_by', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('tvfy_code', models.CharField(db_column='tvfy', db_index=True, max_length=11, unique=True)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('storyline', models.TextField(db_column='storyline', null=True)),
                ('release_date', models.DateTimeField(db_column='release_date', null=True)),
                ('run_time', models.PositiveIntegerField(db_column='run_time', null=True)),
                ('wins', models.PositiveIntegerField(db_column='wins', null=True)),
                ('nominations', models.PositiveIntegerField(db_column='nominations', null=True)),
                ('oscar_wins', models.PositiveIntegerField(db_column='oscar_wins', null=True)),
                ('oscar_nominations', models.PositiveIntegerField(db_column='oscar_nominations', null=True)),
                ('imdb_rate', models.FloatField(db_column='imdb_rate', null=True)),
                ('imdb_vote_count', models.PositiveIntegerField(db_column='imdb_vote_count', null=True)),
                ('imdb_popularity', models.PositiveIntegerField(db_column='imdb_popularity', null=True)),
                ('imdb_url', models.URLField(db_column='imdb_url', db_index=True, null=True, unique=True)),
                ('rt_audience_rate', models.PositiveIntegerField(db_column='rt_audience_rate', null=True)),
                ('rt_audience_count', models.PositiveIntegerField(db_column='rt_audience_count', null=True)),
                ('rt_tomatometer_rate', models.PositiveIntegerField(db_column='rt_tomatometer_rate', null=True)),
                ('rt_tomatometer_count', models.PositiveIntegerField(db_column='rt_tomatometer_count', null=True)),
                ('rotten_tomatoes_url', models.URLField(db_column='rotten_tomatoes_url', db_index=True, null=True, unique=True)),
                ('budget_amount', models.PositiveIntegerField(db_column='budget_amount', null=True)),
                ('budget_currency', models.CharField(db_column='budget_currency', max_length=3, null=True)),
                ('usa_ow_amount', models.PositiveIntegerField(db_column='usa_ow_amount', null=True)),
                ('usa_ow_currency', models.CharField(db_column='usa_ow_currency', max_length=3, null=True)),
                ('ww_amount', models.PositiveIntegerField(db_column='ww_amount', null=True)),
                ('ww_currency', models.CharField(db_column='ww_currency', max_length=3, null=True)),
                ('metacritic_score', models.PositiveIntegerField(db_column='metacritic_score', null=True)),
                ('country', models.ManyToManyField(db_column='country', to='country.country')),
                ('director', models.ForeignKey(db_column='director', null=True, on_delete=django.db.models.deletion.CASCADE, to='director.director')),
                ('genres', models.ManyToManyField(db_column='genres', to='genre.genre')),
                ('language', models.ManyToManyField(db_column='language', to='language.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(db_column='character_name', default='John Doe', max_length=255)),
                ('actor', models.ForeignKey(db_column='actor', on_delete=django.db.models.deletion.CASCADE, to='actor.actor')),
                ('movie', models.ForeignKey(db_column='movie', on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
