# Generated by Django 3.2.5 on 2021-07-30 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0002_auto_20210117_1530'),
        ('actor', '0001_initial'),
        ('core', '0001_initial'),
        ('director', '0002_auto_20210220_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvfy_code', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('creator', models.CharField(blank=True, max_length=128, null=True)),
                ('storyline', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('run_time', models.PositiveIntegerField(blank=True, null=True)),
                ('rt_tomatometer', models.PositiveIntegerField(blank=True, null=True)),
                ('rt_tomatometer_count', models.PositiveIntegerField(blank=True, null=True)),
                ('rt_audience_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('rt_audience_rate_count', models.PositiveIntegerField(blank=True, null=True)),
                ('imdb_popularity', models.PositiveIntegerField(blank=True, null=True)),
                ('imdb_rate', models.FloatField(blank=True, null=True)),
                ('imdb_vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('wins', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('nominations', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('budget', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('usa_opening_weekend', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('ww_gross', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('imdb_url', models.URLField(blank=True, null=True)),
                ('rotten_tomatoes_url', models.URLField(blank=True, null=True)),
                ('country', models.ManyToManyField(to='core.Country')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.director')),
                ('genres', models.ManyToManyField(to='genre.Genre')),
                ('language', models.ManyToManyField(to='core.Language')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(default='John Doe', max_length=255)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
