# Generated by Django 3.2.5 on 2021-09-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="rt_audience_rate_count",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="rt_tomatometer",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="rt_tomatometer_count",
        ),
        migrations.AddField(
            model_name="movie",
            name="budget_currency",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="rt_tomatometer_rate",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="usa_opening_weekend_currency",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="budget",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb_popularity",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb_rate",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb_vote_count",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="nominations",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rt_audience_rate",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="run_time",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="tvfy_code",
            field=models.CharField(db_index=True, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="wins",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
