# Generated by Django 3.1.2 on 2021-02-20 12:07

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("director", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="director",
            old_name="born",
            new_name="born_date",
        ),
        migrations.RenameField(
            model_name="director",
            old_name="died",
            new_name="died_date",
        ),
        migrations.AlterField(
            model_name="director",
            name="died_at",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="director_died_at",
                to="core.country",
            ),
        ),
        migrations.AlterField(
            model_name="director",
            name="perks",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=32),
                null=True,
                size=None,
            ),
        ),
    ]
