# Generated by Django 3.1.2 on 2021-02-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("director", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="director",
            name="born",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="director",
            name="born_at",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="director",
            name="died",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="director",
            name="died_at",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="director",
            name="hits",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="director",
            name="imdb_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="director",
            name="nominations",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="director",
            name="wins",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
