# Generated by Django 3.2.5 on 2021-09-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("director", "0002_auto_20210220_1207"),
    ]

    operations = [
        migrations.RenameField(
            model_name="director",
            old_name="imdb_url",
            new_name="imdb_director_url",
        ),
        migrations.RenameField(
            model_name="director",
            old_name="rt_url",
            new_name="rt_director_url",
        ),
    ]
