# Generated by Django 3.1.2 on 2021-02-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("director", "0002_auto_20210208_1942"),
    ]

    operations = [
        migrations.AddField(
            model_name="director",
            name="rt_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
